FROM golang:alpine

WORKDIR /build

COPY go.mod go.sum ./
COPY ./cmd/batch ./cmd/batch/
COPY ./internal ./internal/

VOLUME ["/var/log/"]

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /batch ./cmd/batch

CMD [ "/batch" ]